### ISSUE TITLE
Image Manager throws error when saving under Joomla 3.9.1

### ISSUE THREAD

**Issue by MarkBretl** [JoomGallery/JoomGallery#172]
Similar to bug previously reported with Joomla 3.8.12, when trying to save an edit in Image Manager under Joomla 3.9.1 the following error message is put up, even if I don't make any changes to that image.

Error
RuntimeException: Invalid field: cid in /homepages/36/d154451060/htdocs/clickandbuilds/Joomla/ReUsies/libraries/src/Form/Form.php:2079 Stack trace: #0 /homepages/36/d154451060/htdocs/clickandbuilds/Joomla/ReUsies/libraries/src/Form/Form.php(1226): Joomla\CMS\Form\Form->validateField(Object(SimpleXMLElement), '', '41', Object(Joomla\Registry\Registry)) #1 /homepages/36/d154451060/htdocs/clickandbuilds/Joomla/ReUsies/administrator/components/com_joomgallery/models/image.php(1010): Joomla\CMS\Form\Form->validate(Array) #2 /homepages/36/d154451060/htdocs/clickandbuilds/Joomla/ReUsies/administrator/components/com_joomgallery/models/image.php(247): JoomGalleryModelImage->_validate(Object(Joomla\CMS\Form\Form), Array) #3 /homepages/36/d154451060/htdocs/clickandbuilds/Joomla/ReUsies/administrator/components/com_joomgallery/controllers/images.php(462): JoomGalleryModelImage->store() #4 /homepages/36/d154451060/htdocs/clickandbuilds/Joomla/ReUsies/libraries/src/MVC/Controller/BaseController.php(710): JoomGalleryControllerImages->save() #5 /homepages/36/d154451060/htdocs/clickandbuilds/Joomla/ReUsies/administrator/components/com_joomgallery/joomgallery.php(68): Joomla\CMS\MVC\Controller\BaseController->execute('save') #6 /homepages/36/d154451060/htdocs/clickandbuilds/Joomla/ReUsies/libraries/src/Component/ComponentHelper.php(402): require_once('/homepages/36/d...') #7 /homepages/36/d154451060/htdocs/clickandbuilds/Joomla/ReUsies/libraries/src/Component/ComponentHelper.php(377): Joomla\CMS\Component\ComponentHelper::executeComponent('/homepages/36/d...') #8 /homepages/36/d154451060/htdocs/clickandbuilds/Joomla/ReUsies/libraries/src/Application/AdministratorApplication.php(101): Joomla\CMS\Component\ComponentHelper::renderComponent('com_joomgallery') #9 /homepages/36/d154451060/htdocs/clickandbuilds/Joomla/ReUsies/libraries/src/Application/AdministratorApplication.php(159): Joomla\CMS\Application\AdministratorApplication->dispatch() #10 /homepages/36/d154451060/htdocs/clickandbuilds/Joomla/ReUsies/libraries/src/Application/CMSApplication.php(196): Joomla\CMS\Application\AdministratorApplication->doExecute() #11 /homepages/36/d154451060/htdocs/clickandbuilds/Joomla/ReUsies/administrator/index.php(51): Joomla\CMS\Application\CMSApplication->execute() #12 {main}

**Comment by MarkBretl** [comment]
Tried reversing the code to fix #166 and it works fine.

**Comment by MrMusic** [comment]
Hi,
the repo JoomGallery/JoomGallery is outdated and is no longer supported.
Please use JoomGalleryfriends/JoomGallery or the support forum at https://www.joomgalleryfriends.net instead.
