### ISSUE TITLE
Image Manager RuntimeException: Invalid field: Image ID

### ISSUE THREAD

**Issue by bassimatteo** [JoomGallery/JoomGallery#176]
When trying to save an edit in Image Manager under Joomla 3.9.11 the following error message is put up, even if I don't make any changes to that image.

`RuntimeException: Invalid field: Image ID in /web/htdocs/www.********.it/home/libraries/src/Form/Form.php:2114 Stack trace: #0 /web/htdocs/www.********.it/home/libraries/src/Form/Form.php(1226): Joomla\CMS\Form\Form->validateField(Object(SimpleXMLElement), '', '68', Object(Joomla\Registry\Registry)) #1 /web/htdocs/www.*********.it/home/administrator/components/com_joomgallery/models/image.php(1010): Joomla\CMS\Form\Form->validate(Array) #2 /web/htdocs/www.**********.it/home/administrator/components/com_joomgallery/models/image.php(247): JoomGalleryModelImage->_validate(Object(Joomla\CMS\Form\Form), Array) #3 /web/htdocs/www.**********.it/home/administrator/components/com_joomgallery/controllers/images.php(462): JoomGalleryModelImage->store() #4 /web/htdocs/www.******.it/home/libraries/src/MVC/Controller/BaseController.php(710): JoomGalleryControllerImages->save() #5 /web/htdocs/www.******.it/home/administrator/components/com_joomgallery/joomgallery.php(68): Joomla\CMS\MVC\Controller\BaseController->execute('save') #6 /web/htdocs/www.******..it/home/libraries/src/Component/ComponentHelper.php(402): require_once('/web/htdocs/www...') #7 /web/htdocs/www.******..it/home/libraries/src/Component/ComponentHelper.php(377): Joomla\CMS\Component\ComponentHelper::executeComponent('/web/htdocs/www...') #8 /web/htdocs/www.******..it/home/libraries/src/Application/AdministratorApplication.php(101): Joomla\CMS\Component\ComponentHelper::renderComponent('com_joomgallery') #9 /web/htdocs/www.******..it/home/libraries/src/Application/AdministratorApplication.php(159): Joomla\CMS\Application\AdministratorApplication->dispatch() #10 /web/htdocs/www.******..it/home/libraries/src/Application/CMSApplication.php(196): Joomla\CMS\Application\AdministratorApplication->doExecute() #11 /web/htdocs/www.******..it/home/administrator/index.php(51): Joomla\CMS\Application\CMSApplication->execute() #12 {main}`

**Comment by seobent** [comment]
How did you solved this?

**Comment by MrMusic** [comment]
Hi,
the repo JoomGallery/JoomGallery is outdated and is no longer supported.
Please use JoomGalleryfriends/JoomGallery or the support forum at https://www.joomgalleryfriends.net instead.
